questions = [
    {"question": "The mathematical constant e is approximately equal to 2.718.", "answer": True},
    {"question": "The Great Wall of China is visible from the Moon.", "answer": False},
    {"question": "Gold is the only metal that is naturally yellow.", "answer": True},
    {"question": "The speed of light in a vacuum is exactly 299,792,458 meters per second.", "answer": True},
    {"question": "Sharks are mammals.", "answer": False},
    {"question": "The human body has four lungs.", "answer": False},
    {"question": "Lightning never strikes the same place twice.", "answer": False},
    {"question": "Venus is the hottest planet in the Solar System.", "answer": True},
    {"question": "DNA stands for Deoxyribonucleic Acid.", "answer": True},
    {"question": "Water boils at 100 degrees Celsius at standard atmospheric pressure.", "answer": True},
    {"question": "A year on Mercury is longer than a day on Mercury.", "answer": True},
    {"question": "Mount Everest is the tallest mountain in the world when measured from base to peak.", "answer": False},
    {"question": "Antarctica is the driest continent on Earth.", "answer": True},
    {"question": "The human heart has three chambers.", "answer": False},
    {"question": "Sound travels faster in air than in water.", "answer": False},
    {"question": "There are more atoms in a glass of water than glasses of water in all the oceans on Earth.", "answer": True},
    {"question": "The Amazon rainforest produces 20% of the Earth's oxygen.", "answer": False},
    {"question": "Albert Einstein won the Nobel Prize for his theory of relativity.", "answer": False},
    {"question": "A nanometer is one-billionth of a meter.", "answer": True},
    {"question": "The human brain stops producing neurons after birth.", "answer": False},
    {"question": "The capital of Australia is Sydney.", "answer": False},
    {"question": "Julius Caesar was the first emperor of Rome.", "answer": False},
    {"question": "The Eiffel Tower was originally intended to be dismantled after 20 years.", "answer": True},
    {"question": "The chemical symbol for silver is Ag.", "answer": True},
    {"question": "Bananas are berries.", "answer": True},
    {"question": "Coca-Cola was originally green.", "answer": False},
    {"question": "The total surface area of human lungs is approximately the size of a football field.", "answer": True},
    {"question": "Octopuses have three hearts.", "answer": True},
    {"question": "The Sahara Desert is the largest desert in the world.", "answer": False},
    {"question": "A jiffy is an actual unit of time.", "answer": True},
    {"question": "The Pacific Ocean is the largest ocean on Earth.", "answer": True},
    {"question": "Birds evolved from dinosaurs.", "answer": True},
    {"question": "Honey never spoils.", "answer": True},
    {"question": "The planet Saturn is less dense than water.", "answer": True},
    {"question": "A blue whale’s heart weighs about as much as a small car.", "answer": True},
    {"question": "The Andromeda Galaxy is moving toward the Milky Way.", "answer": True},
    {"question": "The unicorn is the national animal of Scotland.", "answer": True},
    {"question": "The Earth is closer to the Sun in summer.", "answer": False},
    {"question": "Penguins can fly.", "answer": False},
    {"question": "There are 206 bones in the adult human body.", "answer": True},
    {"question": "The element with the highest melting point is tungsten.", "answer": True},
    {"question": "Pluto is still classified as a planet.", "answer": False},
    {"question": "Neutron stars are denser than black holes.", "answer": False},
    {"question": "The Mona Lisa has no eyebrows.", "answer": True},
    {"question": "One light-year is about 9.46 trillion kilometers.", "answer": True},
    {"question": "Humans share approximately 60% of their DNA with bananas.", "answer": True},
    {"question": "A day on Mars is longer than a day on Earth.", "answer": True},
    {"question": "A water molecule consists of two hydrogen atoms and one oxygen atom.", "answer": True},
    {"question": "The Richter scale measures temperature.", "answer": False},
    {"question": "Venus rotates in the opposite direction to most planets.", "answer": True},
    {"question": "The speed of sound is faster in steel than in air.", "answer": True},
    {"question": "All mammals have four-chambered hearts.", "answer": True},
    {"question": "The first programmable computer was invented in the 20th century.", "answer": True},
    {"question": "An ostrich’s eye is bigger than its brain.", "answer": True},
    {"question": "The chemical element with the atomic number 1 is helium.", "answer": False},
    {"question": "The longest river in the world is the Amazon River.", "answer": True},
    {"question": "The hottest temperature ever recorded on Earth was over 56 degrees Celsius (134°F).", "answer": True}
  ]
  